spring:
  datasource:
    url: jdbc:h2:./db/qma;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: update
      cache:
        use_second_level_cache: true
        use_query_cache: true
        region:
          factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
    properties:
      hibernate:
        show_sql: true